### ISSUE TITLE
Release 3.12 referred in README.md but does not exist.

### ISSUE THREAD

**Issue by stvhwrd** [willfarrell/alfred-pkgman-workflow#100]
The link points to [Download v3.12](https://github.com/willfarrell/alfred-pkgman-workflow/releases/download/3.12/Package.Managers.alfredworkflow), that release [does not exist](https://github.com/willfarrell/alfred-pkgman-workflow/releases/) at this time.

**Comment by jeffbyrnes** [comment]
I’ve gone ahead & fixed that. To be sure it’s clear, I’ve uploaded the version of `Package Managers.alfredworkflow` from f49ff3c as v3.12.
