### ISSUE TITLE
Cache location missing on v3

### ISSUE THREAD

**Issue by willfarrell** [willfarrell/alfred-pkgman-workflow#101]
in /path/to/workflow/code/Workflow.php we use 

```php
$this->cache = $this->home. "/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/".$this->bundle;
		$this->data  = $this->home. "/Library/Application Support/Alfred 2/Workflow Data/".$this->bundle;
```

At some point after you upgrade your v2 cache will be removed my Apple, you'll need to updat to the follow when that happens.

```php
$this->cache = $this->home. "/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/".$this->bundle;
		$this->data  = $this->home. "/Library/Application Support/Alfred 3/Workflow Data/".$this->bundle;
```

Need to find a way to catch this in the background.

**Comment by jeffbyrnes** [comment]
@willfarrell it should be noted that Alfred provides env vars for these locations properly:

* `alfred_workflow_cache`
* `alfred_workflow_data`

In PHP, you’d access them like so:

```php
$cache_path = getenv('alfred_workflow_cache');
$data_path = getenv('alfred_workflow_data');
```

Full docs on [script environment variables](https://www.alfredapp.com/help/workflows/script-environment-variables/) and [using variables in workflows](https://www.alfredapp.com/help/workflows/advanced/variables/). Also helpful is this recent [HOW TO from the forums](http://www.alfredforum.com/topic/9070-how-to-workflowenvironment-variables/).

**Comment by willfarrell** [comment]
Had no idea. Let's add those in then.

**Comment by willfarrell** [comment]
done v3.15
