### ISSUE TITLE
npm not working anymore

### ISSUE THREAD

**Issue by vroudge** [willfarrell/alfred-pkgman-workflow#105]
Hey Will!

First of all, thanks for your AWESOME workflows. I use them a lot and you make my life so much easier. Much love to you.

Just a word to tell you that NPM updated its search engine and it seems your workflow does not work anymore with it.

**Comment by willfarrell** [comment]
npm was updated in https://github.com/willfarrell/alfred-pkgman-workflow/pull/103 by @jgarber623.

Are you running the latest version?

**Comment by vroudge** [comment]
Oh my bad. Just installed an older version that I had in my downloads directory. Nevermind!

Thanks for the quick answer.
