### ISSUE TITLE
Brew search doesn't work

### ISSUE THREAD

**Issue by schrodincat** [willfarrell/alfred-pkgman-workflow#118]
Brew search doesn't work:
![screen shot 2017-10-30 at 13 51 16](https://user-images.githubusercontent.com/13354491/32167329-a0781f52-bd79-11e7-8862-51c4358bffbd.jpg)
Is it supposed not to show search results in Alfred only generating link with search query?
I have Workflow 3.21, Alfred 3.5.1.

**Comment by jeffbyrnes** [comment]
I can verify this does not work for me, either.

**Comment by josselinauguste** [comment]
I submitted https://github.com/willfarrell/alfred-pkgman-workflow/pull/132 to fix it
