### ISSUE TITLE
Bower search doesn't work

### ISSUE THREAD

**Issue by andreiborisov** [willfarrell/alfred-pkgman-workflow#119]
Bower search doesn't work:
<img width="593" alt="screen shot 2017-10-30 at 14 49 39" src="https://user-images.githubusercontent.com/13354491/32169504-cf2b515e-bd81-11e7-843b-25ce6211ca73.png">
I have Workflow 3.21, Alfred 3.5.1.

**Comment by jeffbyrnes** [comment]
I can verify this does not work for me, either.
