### ISSUE TITLE
Grunt search doesn't work

### ISSUE THREAD

**Issue by andreiborisov** [willfarrell/alfred-pkgman-workflow#120]
Grunt search doesn't work:
<img width="593" alt="screen shot 2017-10-30 at 14 47 29" src="https://user-images.githubusercontent.com/13354491/32169526-e7f960b8-bd81-11e7-8489-1141bfd9a850.png">
I have Workflow 3.21, Alfred 3.5.1.

**Comment by jeffbyrnes** [comment]
I can verify this does not work for me, either.
