### ISSUE TITLE
Elixir Hex Packages search doesn't work

### ISSUE THREAD

**Issue by schrodincat** [willfarrell/alfred-pkgman-workflow#123]
Elixir Hex Packages search doesn't work:
![screen shot 2017-10-30 at 21 25](https://user-images.githubusercontent.com/13354491/32188881-15d692de-bdba-11e7-901b-c0322e63f4fa.jpeg)
I have Workflow 3.21, Alfred 3.5.1.

**Comment by sb8244** [comment]
Comes back with ```
object(stdClass)#4 (2) {
  ["message"]=>
  string(29) "User-Agent header is required"
  ["status"]=>
  int(400)
}
```

Looking into a fix
