### ISSUE TITLE
Rasberry Pi Packages search doesn't work

### ISSUE THREAD

**Issue by andreiborisov** [willfarrell/alfred-pkgman-workflow#125]
Rasberry Pi Packages search doesn't work:
![screen shot 2017-10-30 at 21 28](https://user-images.githubusercontent.com/13354491/32188932-3fe2d1d2-bdba-11e7-9732-6d3de8c9c553.jpeg)
I have Workflow 3.21, Alfred 3.5.1.

**Comment by mfsp3** [comment]
> Rasberry Pi Packages search doesn't work:
> 
> ![screen shot 2017-10-30 at 21 28](https://user-images.githubusercontent.com/13354491/32188932-3fe2d1d2-bdba-11e7-9732-6d3de8c9c553.jpeg)
> 
> I have Workflow 3.21, Alfred 3.5.1.
