### ISSUE TITLE
Homebrew Packages search doesn't work

### ISSUE THREAD

**Issue by christopherdwhite** [willfarrell/alfred-pkgman-workflow#133]
Homebrew packages don't appear to work at the moment and even the 'Click to see the results for yourself' points to a 404.

<img width="853" alt="hyper 2018-06-17 14-27-31" src="https://user-images.githubusercontent.com/1746405/41511794-3dc28722-723b-11e8-93b7-cb5f78604bc5.png">

**Comment by Charles-Catta** [comment]
The script for searching Homebrew uses [Braumeister](https://github.com/Homebrew/braumeister) which has been deprecated taking https://formulae.brew.sh/search/ out with it.

A solution would be to use another endpoint like http://searchbrew.com/

**Comment by willfarrell** [comment]
I'm open to a PR if someone wants to take this on.
