### ISSUE TITLE
The plugin seems to not work correctly out of the box

### ISSUE THREAD

**Issue by davidawad** [willfarrell/alfred-pkgman-workflow#161]
For some reason after installing the workflow I can see that the search options are there from the plugin but they just don't work. 

What would cause the hotkeys to not properly parse the input like this? 

Thanks for any help

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/4019054/160058897-d4e68ff7-2e48-4d58-b6e5-206c9922165a.png">

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/4019054/160058918-c492f2be-5bfd-40cd-99cb-c4c56b24771f.png">

**Comment by davidawad** [comment]
I have other workflows that work without issue. 

(For example the hash workflow works on my alfred install with no issues : https://github.com/willfarrell/alfred-hash-workflow) 

I just realized you wrote that one as well, thanks @willfarrell ! 😂

**Comment by jeffbyrnes** [comment]
@davidawad that _may_ be related to how the workflow uses PHP under the covers, and macOS Monterey no longer includes a copy of PHP (see #158 #159 #157 #160)

I’m hoping to spend some cycles sprucing up the workflow in a big way sometime soon, as it’s not working well for me, either.

**Comment by jeffbyrnes** [comment]
Nope, this is a case, at least for the Yeoman search, of that particular search not working well. Fix incoming!
