### ISSUE TITLE
Can't seem to run the workflow correctly - macbook pro m1 max

### ISSUE THREAD

**Issue by bangelischan** [willfarrell/alfred-pkgman-workflow#162]
Hi, I'm running MacOS 12.3.1 on a M1 mac && running Alfred 4.6.4.

It seems like I cant run the workflow correctly. When I run the "debug mode", here's what it says : 
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/46763189/164770707-1d67dead-cdb7-4f10-89d0-e2d778deafe7.png">

`JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:`

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/46763189/164770776-b467f593-ba66-47e9-bbe7-6503a86c1c6d.png">

I looked up the error but I can't seem to find the answer I'm looking for.

**Comment by jeffbyrnes** [comment]
@bangelischan do you have PHP installed? It no longer comes with macOS, so that may be at fault.

**Comment by bangelischan** [comment]
Yes!

As you can see on the second screenshot,
It’s installed under /opt/homebrew/bin/php

**Comment by jeffbyrnes** [comment]
Hmmm! I’m on an Intel Mac, macOS 12.3.1, Alfred 4.6.4, Package Managers workflow v5.0.0, and it’s working OK for me:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/260553/164912904-b192efb7-795b-4009-935b-14012f476377.png">

Maybe try grabbing the workflow freshly? Might also be an Apple Silicon thing w/ where PHP is installed…?

**Comment by bangelischan** [comment]
I think it might be a problem with PHP. What's your version of php ? (under /opt/homebrew/php) 
And could I also see ur setup when you click on the "Brew" box in the workflow?
![image](https://user-images.githubusercontent.com/46763189/164913919-4490ebf5-8262-48b1-9b2b-3e28b89d1b54.png)
![image](https://user-images.githubusercontent.com/46763189/164913921-965ee75f-0d18-4c66-b5ae-2a751023fce5.png)

Thank you.

**Comment by bangelischan** [comment]
Does anyone have an idea ?

**Comment by jun6lee** [comment]
Doesn't work for me on Intel either.

Have tried changing Language to  /usr/local/bin/php as well as the default /bin/bash
Tried adding shebang in the brew.php of #!/usr/bin/env php

No joy.

@jeffbyrnes -- would you mind sharing a similar screenshot and tell us which version of PHP specifically you have installed via brew? It might help us troubleshoot this.

**Comment by jeffbyrnes** [comment]
Sure thing:

```bash
🕙 17:48:26 jeffbyrnes in WebsterParser on  main via  v18.0.0
♠ which php
/usr/local/bin/php

🕙 14:35:14 jeffbyrnes in WebsterParser on  main via  v18.0.0
♠ php -v
PHP 8.1.5 (cli) (built: Apr 16 2022 00:14:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.5, Copyright (c), by Zend Technologies
```

Latest & greatest, installed via Homebrew. here’s the workflow:

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/260553/166802978-b10d069d-2f28-40db-90f3-fe0204e04301.png">

Do y’all have the `PATH` env var set in “Workflow Environment Variables”?

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/260553/166803051-667b4bd6-75d3-42e2-849d-99f26269af65.png">

**Comment by bangelischan** [comment]
Oh. That just fixed it =D 
Forgot about the PATH. 

Thank you!

**Comment by jun6lee** [comment]
Mine was another oddity after applying PATH
com.farrell.pkgman.alfredworkflow was not present under: 
/Users/MYSUSER/Library/Application Support/Alfred/Workflow Data/

Creating such a directory manually fixed it.

**Comment by bangelischan** [comment]
Nice !
