### ISSUE TITLE
Can't open the browser

### ISSUE THREAD

**Issue by zhiyicai** [willfarrell/alfred-pkgman-workflow#164]
Can't open the browser
<img width="1352" alt="Sceenshot7726906" src="https://user-images.githubusercontent.com/13891311/167293635-17f8b93f-5eeb-46df-a956-b25b1cec4380.png">

Alfred 4.6.5 [1299]
macos Monterey 12.0.1
PHP 8.1.2

**Comment by jeffbyrnes** [comment]
@zhiyicai hmm, this appears to be something unusual to your setup.

Do you have the `PATH` env var set in the workflow? This would _seem_ to be a `PATH` issue.

If you open a shell (using Terminal or iTerm), what do you get when you run this command?

```bash
which cut
```
