### ISSUE TITLE
can package info add updatetime?

### ISSUE THREAD

**Issue by fireinrain** [willfarrell/alfred-pkgman-workflow#167]

**Comment by jeffbyrnes** [comment]
@fireinrain to make sure I understand you correctly, you want the date & time of when each search result was last updated

I.e., along with name, version, and description, you want to also show “last updated” in the list of results?

**Comment by fireinrain** [comment]
> @fireinrain to make sure I understand you correctly, you want the date & time of when each search result was last updated
> 
> I.e., along with name, version, and description, you want to also show “last updated” in the list of results?

I am so sorry I dont make me clearly. I mean, add the package latest version release date, so that this workflow can fetch this  
data and put it on the alfred result box.

**Comment by jeffbyrnes** [comment]
@fireinrain all good! Thanks for clarifying.

There’s limited space for each item in a list of Alfred items, so name, version, and a brief description seems to be the most vital things to show.

So I don’t think we can fit this in, but thankfully, if you action (type the “return” or “enter” key, or click/tap) on an item, it should take you to the individual page for that repository item & there you can find out more about it.

This probably isn’t what you’re looking for, but we’re only got so much space. I hope that makes sense!
