### ISSUE TITLE
Removing OneUpdater for Alfred Gallery

### ISSUE THREAD

**Issue by vitorgalvao** [willfarrell/alfred-pkgman-workflow#171]
When [the Alfred Gallery](https://www.alfredforum.com/topic/19058-submitting-workflows-for-the-alfred-gallery/) is live, added workflows will be updatable from within Alfred itself. As part of that, a prerequisite for inclusion will be that workflows *not* auto-update themselves. This is to avoid a confusing interaction of crossed updates *and* for security reasons, as Gallery workflows go through a number of checks.

Your development process won’t change. You’ll still make GitHub releases as usual to update the workflow. We’ll detect when new releases are out and queue them up for a new review and update in the Gallery.

I started with a PR for this, but since you have a build process you may prefer to do it yourself. Making a new release helps to speed up the process, but if you prefer to wait I’ll ping you again once the Gallery is live.

**Comment by jeffbyrnes** [comment]
@vitorgalvao by all means please go ahead with your PR! If there’s anything that needs tweaking, we can adjust.
