### ISSUE TITLE
Removing PATH variable

### ISSUE THREAD

**Issue by vitorgalvao** [willfarrell/alfred-pkgman-workflow#172]
As [pointed out](https://github.com/willfarrell/alfred-pkgman-workflow/commit/519e763096c29d5c683ce0bbd5901cf9c63e1d55#r69650298), `${PATH}` won’t expand from a Workflow Environment Variable; it’s not a shell.

But the variable isn’t necessary at all anymore for Alfred 5, since it [includes the Homebrew paths](https://www.alfredapp.com/help/workflows/advanced/understanding-scripting-environment/).

**Comment by shotcowboystyle** [comment]
I had the same problem where it wasn't working, and always defaulting to a Google Search. I just deleted the workflow and re-added it and now everything is working normally again.

**Comment by vitorgalvao** [comment]
That’s unrelated. The variable in there isn’t harmful, it’s just unnecessary and doesn’t work as the creator expects.
