### ISSUE TITLE
XDebug Trigger should probably be a checkbox

### ISSUE THREAD

**Issue by vitorgalvao** [willfarrell/alfred-pkgman-workflow#174]
What are the valid values for `XDEBUG_TRIGGER`? If they’re `0` and `1`, that’s what the checkbox returns and it makes more sense than a Text Field.

But I don’t see that option documented, it seems to only be useful for yourself during development, right? That being the case, that option can remain as a Workflow Environment Variable because it’s not something users will ever want to change (i.e. it’s not user-facing configuration).

**Comment by willfarrell** [comment]
Go for it.
