### ISSUE TITLE
Duplicate database file on every key stroke

### ISSUE THREAD

**Issue by eugenesvk** [willfarrell/alfred-pkgman-workflow#178]
When trying to search for e.g. `brew mega` I get the following files created in `Alfred/Workflow Data/com.farrell.pkgman.alfredworkflow/`
brew-cask.json
brew-cask.m.json
brew-cask.me.json
brew-cask.meg.json
brew-cask.mega.json
brew-formula.json
brew-formula.m.json
brew-formula.me.json
brew-formula.meg.json
brew-formula.mega.json

this takes some time, but after all the files are created I get my search results
v6.0.3
🍏13.4.1

**Comment by jeffbyrnes** [comment]
@eugenesvk thanks for sharing this. If I get a chance, I’ll try to track down what’s going on here.
