### ISSUE TITLE
Add go packages

### ISSUE THREAD

**Issue by learn2reid** [willfarrell/alfred-pkgman-workflow#180]

**Comment by learn2reid** [comment]
activity?

**Comment by jeffbyrnes** [comment]
@learn2reid I would say if you’d like to see those added, please go ahead & submit a pull request! I don’t do much with Go myself, and I’ve no idea if @willfarrell does.

**Comment by learn2reid** [comment]
I tried to give it a shot but wasn't successful. Ok, thank you. Appreciate your work
