### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by willfarrell** [willfarrell/alfred-pkgman-workflow#20]
https://sublime.wbond.net/

**Comment by wbond** [comment]
FYI, the correct URL is now https://packagecontrol.io. The whole site is an API, where you can append `.json` to any data-driven page's URL.

**Comment by jeffbyrnes** [comment]
@wbond that is pretty sweet. Definitely a great candidate for this workflow, @willfarrell!

**Comment by willfarrell** [comment]
What! That's awesome. Should be an easy workflow to build. @wbond Interested in making a PR?

**Comment by wbond** [comment]
I don't personally use Alfred, and am kinda busy with other open source projects, just figured I'd add some info since someone pointed me towards the project.

**Comment by willfarrell** [comment]
Thanks and no worries. I'm sure when someone needs it we can build it.

**Comment by sou-lab** [comment]
I want This one

**Comment by willfarrell** [comment]
Keyword `st` added for Sublime Text.
