### ISSUE TITLE
PEAR search returns “register” link as search result

### ISSUE THREAD

**Issue by jeffbyrnes** [willfarrell/alfred-pkgman-workflow#45]
Due to this search being a regex parsing of the search results page HTML, the first item in any PEAR search seems to be “Register”, with the description being part of the HTML for that link.

Tightening up the regex might help, or perhaps there’s an actual API that can be queried instead of doing regex parsing.

If I get a chance, I’ll fix this up myself & issue a PR.

**Comment by jeffbyrnes** [comment]
@willfarrell did some new code fix this up?

**Comment by willfarrell** [comment]
Thought it was in you PR. I took care of it. See v2.10. Good catch.
