### ISSUE TITLE
Optimize first lookup

### ISSUE THREAD

**Issue by raine** [willfarrell/alfred-pkgman-workflow#51]
Is there any way you could optimize the way for example `npm` workflow performs the first search?

For instance, it seems that when I type `npm ramda` it will first perform npm search with empty string, because I initially get the message "Minimum query length not met". It takes about 1-2 seconds after that to get the real result.

Sometimes it might search first for `r` before finally searching `ramda`. I don't type particularly slow.

I realize this is not a terribly big deal but I see some room for improvement.

Thanks!

**Comment by willfarrell** [comment]
Removed message when query length == 0
See v2.5

**Comment by raine** [comment]
Thanks @willfarrell

I realized that for me it works best to use custom search to go directly to `npmjs.com/package/{query}` and then google npm separately if I'm not certain what I'm looking for. I found that with this workflow it takes too long to get to a result when I already know the package name.

**Comment by willfarrell** [comment]
I know the feeling. I thought about creating a custom search index for each of the repos of a public API server to speed this up, and hopefully get closer to google like speed. Unfortunately I'm a little short on time at the moment.
