### ISSUE TITLE
Brew search seems weird

### ISSUE THREAD

**Issue by ngocphamm** [willfarrell/alfred-pkgman-workflow#55]
A little strange behavior. Searching `nmap` with `brew nma` gets the results while `brew nmap` shows there's no such package.

![screen shot 2015-01-23 at 11 26 14 pm](https://cloud.githubusercontent.com/assets/395123/5886113/d6f76f2c-a357-11e4-9eee-c2dd5fda67f5.png)
![screen shot 2015-01-23 at 11 26 20 pm](https://cloud.githubusercontent.com/assets/395123/5886114/d709f3ae-a357-11e4-807f-ba5a3a44a46b.png)

**Comment by willfarrell** [comment]
Interesting, it looks like when there is an exact match the the search url get redirected to the formula page, breaking the regex parser. I'll see if I can whip up a solution.

**Comment by willfarrell** [comment]
Check out v2.9 for an update. You may need to run `pkgman cleardb` first. Let me know how it works.

**Comment by ngocphamm** [comment]
Working perfectly (for brew) now! Thank you @willfarrell. You are the man!!!

**Comment by willfarrell** [comment]
No problem.
