### ISSUE TITLE
gulp, grunt not working

### ISSUE THREAD

**Issue by marionava** [willfarrell/alfred-pkgman-workflow#59]
gulp and grunt are not working

**Comment by willfarrell** [comment]
They both seem to be working for me. They make take awhile to first show due to the downloading of the data (10sec the first time). If that doesn't work try clearing the cache db `pkgman cleardb`

**Comment by marionava** [comment]
I did what you said, but is not working yet.

I'm attaching you the screens. Only appears this text "No plugins were found that matched "{my_query}" "

![captura de pantalla 2015-02-15 a las 12 18 45](https://cloud.githubusercontent.com/assets/478018/6204324/d2d5a3b6-b50c-11e4-8c82-a0e07bf3d054.png)
![captura de pantalla 2015-02-15 a las 12 19 29](https://cloud.githubusercontent.com/assets/478018/6204326/ed9b2810-b50c-11e4-8499-e054bbeab8fe.png)

**Comment by willfarrell** [comment]
hmmm, `min` is working fine for me. Can you try deleting the workflow and
re-downloading the latest version.

will Farrell
Esq. BASc EIT
Electrical Engineer - University of Waterloo
Cell: (403) 797-0557
willfarrell.ca
PGP Key: willfarrell.ca/pgp
