### ISSUE TITLE
Recheck gulp, puppet, raspbian in v3

### ISSUE THREAD

**Issue by willfarrell** [willfarrell/alfred-pkgman-workflow#63]

**Comment by jeffbyrnes** [comment]
So puppet:

![screen shot 2015-04-21 at 10 34 44 am](https://cloud.githubusercontent.com/assets/260553/7254595/1e0b3228-e812-11e4-93d2-732c1c889650.png)

And raspbian:

![screen shot 2015-04-21 at 10 35 45 am](https://cloud.githubusercontent.com/assets/260553/7254603/2bf27ff4-e812-11e4-86bd-695e8d0e97a7.png)

both look good.

Gulp seems to have tweaked their site, so I think that’s a new issue (I remember it was working when I first rewrote things). I’ll file a new issue to cover that.
