### ISSUE TITLE
React-components

### ISSUE THREAD

**Issue by thibmaek** [willfarrell/alfred-pkgman-workflow#64]
Just another proposition for package manager:
url = http://react-components.com
searchurl = http://react-components.com/search/{query}

**Comment by jeffbyrnes** [comment]
@thibmaek please feel free to submit a PR to add this repository!

**Comment by thibmaek** [comment]
Any guidelines about which variables to modify?
I tried it before but was unsure if I was editing correctly.

**Comment by jeffbyrnes** [comment]
@thibmaek unfortunately, it looks like this site doesn’t offer an API to search the repository; however, upon reading the site itself, this stood out to me:

> Every module registered on NPM using the keyword react-component will show up in the list. It really is that simple.

With that in mind, I’d encourage just using the `npm` search that we already have.

**Comment by thibmaek** [comment]
@jeffbyrnes yeah seems like it does. Gonna close this then.

**Comment by willfarrell** [comment]
You could also create a wrapper shortcut around `npm` for now that would allow you to have a shorthand. Lets keep it open for now and revisit down the road, facebook will likely create an API down the road.

```php
$query = <<<EOD
react-component-{query}
EOD;

require_once('code/Npm.php');

$repo = new WillFarrell\AlfredPkgMan\Npm();
echo $repo->search($query);
```

**Comment by jeffbyrnes** [comment]
That’s true; you could just add that to the workflow itself, rather than even needing to code a new class.

**Comment by willfarrell** [comment]
Looking at the page source, it should be pretty easy to create a class for it. The `npm` class is a great example on parsing search results. You can easily test it form the command line first, `php React.php`, before hooking it up into Alfred.

**Comment by willfarrell** [comment]
Any update on a PR for this?

**Comment by thibmaek** [comment]
I think I have some code left from trying this, I'll have a look tomorrow.

**Comment by willfarrell** [comment]
Thanks, I should be around most of the day if you need a hand.

**Comment by willfarrell** [comment]
See Glup and Cordova as examples for doing this.
