### ISSUE TITLE
npm package lookup no longer opens pages

### ISSUE THREAD

**Issue by petey** [willfarrell/alfred-pkgman-workflow#73]
When I select an item when looking up an npm module, it no longer opens a page at npmjs.com.

**Comment by willfarrell** [comment]
I was noticing that today at work, thought it was one of the many OS X 10.11 bugs.
Hmmm, looks like Alfred crashes when one clicks on workflows in OS X 10.11. Sadly I'll be unable to debug this for you till Alfred pushes a fix. Sorry about that. If you'd like to track down the bug and submit a PR, I'll be more than happy to merge it.

**Comment by joeyvandijk** [comment]
This is also happening on OSX 10.10 where your ```caniuse-workflow``` does work when clicked (or entered). #FYI

**Comment by willfarrell** [comment]
Was finally able to get into Alfred. I got the strangest error. I can debug this after work today.

```bash
[ERROR: alfred.workflow.action.script] The files /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/\, and /Users/willfarrell/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E3A0F8BF-018B-4E39-9D7F-07E0DA1039CA/&nbsp\;&nbsp\;bnjjj do not exist
```

**Comment by joeyvandijk** [comment]
Same here, but if you could ```diff``` between your caniuse-workflow & this workflow, you will probably find more info. Sorry I am not able to file a pull request.

**Comment by willfarrell** [comment]
It's most likely an invalid url is being passed to the open url trigger. Likely a bug from the last version pushed.

**Comment by joeyvandijk** [comment]
Ok, hope so. Previously it worked but now the version-numbers are gone again. Maybe it has to do with the URL/lookup. Thanks for your time/effort!

**Comment by ChiperSoft** [comment]
I'm having this problem in 10.9 as well, Alfred 2.7.1

**Comment by willfarrell** [comment]
Just pushed a fix v3.03
There was a PR with the fix, but didn't have an updated alfredworkflow file

**Comment by ChiperSoft** [comment]
FYI, the readme url still points at 3.02

**Comment by willfarrell** [comment]
Right, I always forget to do the github release stuff. Fixed.

**Comment by joeyvandijk** [comment]
Great thanks for the fix!
