### ISSUE TITLE
New version of the workflow not available on Packal

### ISSUE THREAD

**Issue by itadakimas** [willfarrell/alfred-pkgman-workflow#74]
Hi !

Is there something we can do to help you publish the new version of this workflow on Packal ?

**Comment by jeffbyrnes** [comment]
@itadakimas ah, thanks for the reminder! I’d help with that, but it looks like @willfarrell is the only one with access to [the packal copy of the workflow](http://www.packal.org/workflow/package-managers).

I think it might be time to write some kind of automation for releasing a new version of the workflow…

**Comment by willfarrell** [comment]
Done, not sure how we can automate keeping them up to date.

The workflow can be automatically updated using `Alleyoop` or `Monkey Patch`. They were out before `packal` existed. Alfred really needs to address this issue themselves.

**Comment by itadakimas** [comment]
@willfarrell: apparently, `Alleyoop` and `Monkey Patch` are no longer maintained. And since the Alfred team has posted a Tweet about Packal, I guess it's going to be more "official".

Sources:
* http://www.alfredforum.com/topic/1582-alleyoop-update-alfred-workflows/page-9
* http://www.alfredforum.com/topic/2218-monkey-patch-update-alfred-workflows-via-alleyoop/
* https://twitter.com/alfredapp/status/598519562070564865

**Comment by jeffbyrnes** [comment]
@willfarrell I was more thinking a set of tasks (using Rake, or Grunt, or anything really) to automate some (or maybe all) of the steps needed to cut a new release of the workflow.

**Comment by willfarrell** [comment]
@itadakimas `Alleyoop` and `Monkey Patch` are dead :( . I'll try and remember to keep `Packal` up to date.

**Comment by willfarrell** [comment]
New Issue for keeping Packal up to date #81
