### ISSUE TITLE
"Search on the website"

### ISSUE THREAD

**Issue by boneskull** [willfarrell/alfred-pkgman-workflow#84]
Instead of "Go to the website" as the default action (without arguments), perhaps "Search on the website" may be more helpful.  What do you think?

**Comment by boneskull** [comment]
Also I wanted to say *thank you* for this workflow; I use it every single day, many times a day.  I'd be happy to help with the workflow if my PHP wasn't so rusty.

![thank you](https://media.giphy.com/media/13qctMBrrgbwJi/giphy.gif)

**Comment by jeffbyrnes** [comment]
Not all of the workflows allow for a URL-based search, but I feel as though some of them already do this… hard to say.

Regardless, a feature I find myself wishing for, too!

**Comment by willfarrell** [comment]
All workflows have "Go to the website" as an option. if the package manager has a url that allows searching there is an additional option to "search for ...". was there a particular pkgman that didn't have search but the website for it does? If so, please make a new issue and we can check it out.
