### ISSUE TITLE
search on npmjs.com

### ISSUE THREAD

**Issue by boneskull** [willfarrell/alfred-pkgman-workflow#85]
npmjs.com should be able to be searched, but instead the workflow just says "visit the web site", unless I'm missing something.

**Comment by jeffbyrnes** [comment]
There’s a bit of a quirk with the NPM search; you’ll want to just finish typing out `npm` and then add what you want to search for; it’ll catch up & do the search properly.

Improvements to whether the search actually runs or not definitely need to be made (i.e., when you have yet to actually type anything).
