### ISSUE TITLE
Remove useless default (first) search result if found something

### ISSUE THREAD

**Issue by vanburg** [willfarrell/alfred-pkgman-workflow#88]
Maybe I missing something, but I can't find a way to remove this:
![search on npmjs com issue 85 willfarrell alfred-pkgman-workflow 2016-02-04 07-13-20](https://cloud.githubusercontent.com/assets/600768/12805702/32dc2d70-cb0f-11e5-83f8-443540b9a47c.png)
So instead of just hit Enter I must use `⌘+2`, that's annoying.
BTW, I believe nobody ever use 'Go to rubygems/npm/others' - this can be done by Alfred itself, w/o any workflows :)
This is the example of behaviour I'm looking for: http://www.packal.org/workflow/npm-repo
Is it possible to simply check/uncheck something to accomplish that task, or it will lead to much more complex changes?
Thanks!

**Comment by willfarrell** [comment]
On my computer `go to ...` shows by itself till results are loaded then it jumps to the bottom. Try updating alfred on your machine. hopefully that works for you. I can check out the behaviour of that other npm workflow on Sunday. We try and make all the package manager act the same, the link is usually incase the source of the data changes structure, the user then can jump to a search page online and continue on while we update the workflow.

**Comment by vanburg** [comment]
Alfred version: `2.8.2 (432)`
No changes after  `pkgman cleardb` and Alfred reopen it...

**Comment by vanburg** [comment]
After some research `apt-get nodejs` works as expected...

**Comment by willfarrell** [comment]
Very strange. Maybe it's an alfred caching glitch. I checkout that other npm workflow. It didn't even work on my machine lol. Let me know if it persists after the next version of alfred. I'll shoot them a link to this issue.

**Comment by vanburg** [comment]
Okay ;)
