### ISSUE TITLE
docker does not do search

### ISSUE THREAD

**Issue by Morriz** [willfarrell/alfred-pkgman-workflow#89]
Hi, I have neverrrr seen the docker part of this plugin work. It ALWAYS just returns the same list, without doing anything with the query. Whatever you type, the nginx repo comes on top.

**Comment by willfarrell** [comment]
That's very interesting. I seem to be unable to reproduce this issue. Try running `pkgman cleardb`.
Are you all up to date with Alfred and the Workflow?
<img width="654" alt="screen shot 2016-03-18 at 7 54 49 am" src="https://cloud.githubusercontent.com/assets/1097020/13879752/c7338586-ecde-11e5-936d-12f8c5c197eb.png">

**Comment by Morriz** [comment]
Tnx for the quick reply. But yes, latest of both. I will try clearing the db

**Comment by Morriz** [comment]
Sry, but where can I find pkgman? Not in brew

**Comment by willfarrell** [comment]
Sorry, type `pkgman cleardb` into Alfred.

**Comment by Morriz** [comment]
Clearing and building the cache again didn't do anything, see screenie:

**Comment by willfarrell** [comment]
hmmm, clearing the cache puts the workflow back to the same state it was when it was first installed. The last thing I can suggest to remove and reinstall it.

**Comment by Morriz** [comment]
I finally got the 3.0.9 from GH, but packal lists '3.0.7' and gives 3.0.6...maybe automate packal deploys too?

But it works!! yay!

**Comment by willfarrell** [comment]
If I knew how to automate packal deploys it would be already done. I have updated the package on Packal incase others run into this.
