### ISSUE TITLE
Is there a way to hide' Go to the website' when searching npm?

### ISSUE THREAD

**Issue by nikitavoloboev** [willfarrell/alfred-pkgman-workflow#90]
Here is what I mean : 

![2016-04-27 at 00 04](https://cloud.githubusercontent.com/assets/6391776/14835759/c6defc4a-0c0b-11e6-981f-64fec1740f19.png)

It is also present there when I make some query, for example : 

![2016-04-27 at 00 06](https://cloud.githubusercontent.com/assets/6391776/14835769/d8671aba-0c0b-11e6-98bb-f4a9e7fc5ad4.png)

Is there a way to remove it? Thank you a lot and I hope you can understand what I mean. This is a really amazing workflow.

**Comment by willfarrell** [comment]
I know what you mean.
First off why this happens. Alfred has it's own "memory" that remembers what you've clicked on in the past. What this does is sort items based on usage. This is what causes that like to bubble up to the top every time, it's just been clicked on more than anything else on the list.

Solutions:
#. Remove it completely - likely not going to happen
#. Each item has a unique key associated with it (this is what alfred stores counts for). The `go to website` also does, what we could do is make it's key unique for every search pushing it down the list.

I'm going on vacation soon so I may have to take a look at this when I get back.
