### ISSUE TITLE
Fetch url for Cocoapods

### ISSUE THREAD

**Issue by thibmaek** [willfarrell/alfred-pkgman-workflow#93]
Is there a reason why the workflow fetches from https://cocoadocs.org instead of https://cocoapods.org ?
e.g SwiftyJSON is available on the latter only.

**Comment by willfarrell** [comment]
No idea / I don't remember ... that one was built a long time ago. If the later has a cleaner API and can offer a speed improvement without decreasing the quality. I'd love to merge a PR for it.
